### ISSUE TITLE
Webpack failed to create application bundle

### ISSUE THREAD

**Issue by mathieuleclaire** [scalacenter/scalajs-bundler#192]
Hi,
I am packaging some facade with scalajs-bundler. I added some config-files (to avoid using jquery): 
```js
module.exports = {
      "entry": {
    "demo-opt": [__dirname + "/bootstrapslider-opt.js"]
  },
  "output": {
    "path": __dirname,
    "filename": "[name]-bundle.js"
  },
    resolve: {
        alias: {
             "jquery": __dirname + "../../../resources/jquery-stub.js"
        }
    }
}
```
my built.sbt project is the following: 
```sbt
lazy val bootstrapslider = project.in(file("bootstrapslider")) enablePlugins (ScalaJSBundlerPlugin) settings(
  scalaJsDom,
  querki,
  npmDependencies in Compile += "bootstrap-slider" -> bootstrapSliderVersion,
  jsDependencies += ProvidedJS / "jquery-stub.js",
  webpackConfigFile := Some(baseDirectory.value / "jqueryConfig.config.js")
)
```

on a ```fullOptJS::wepack```, I get:

```sh
sbt:bootstrapslider> fullOptJS::webpack
[info] Writing scalajs.webpack.config.js
[info] Bundling the application with its NPM dependencies
[info] Hash: 8624608efa0a54f8ae83
[info] Version: webpack 3.5.5
[info] Time: 76ms
[info]              Asset     Size  Chunks             Chunk Names
[info] demo-opt-bundle.js  12.6 kB       0  [emitted]  demo-opt
[info]    [0] multi ./bootstrapslider-opt.js 28 bytes {0} [built]
[info]    [1] ./bootstrapslider-opt.js 9.27 kB {0} [built]
[info]    [2] (webpack)/buildin/global.js 509 bytes {0} [built]
[error] java.lang.AssertionError: assertion failed: Webpack failed to create application bundle
[error] 	at scala.Predef$.assert(Predef.scala:219)
[error] 	at scalajsbundler.Webpack$.bundle(Webpack.scala:152)
[error] 	at scalajsbundler.sbtplugin.WebpackTasks$.$anonfun$webpack$2(WebpackTasks.scala:45)
[error] 	at sbt.util.FileFunction$.$anonfun$cached$1(FileFunction.scala:73)
[error] 	at sbt.util.FileFunction$.$anonfun$cached$4(FileFunction.scala:147)
[error] 	at sbt.util.Difference.apply(Tracked.scala:313)
[error] 	at sbt.util.Difference.apply(Tracked.scala:293)
[error] 	at sbt.util.FileFunction$.$anonfun$cached$3(FileFunction.scala:143)
[error] 	at sbt.util.Difference.apply(Tracked.scala:313)
[error] 	at sbt.util.Difference.apply(Tracked.scala:288)
[error] 	at sbt.util.FileFunction$.$anonfun$cached$2(FileFunction.scala:142)
[error] 	at scalajsbundler.sbtplugin.WebpackTasks$.$anonfun$webpack$1(WebpackTasks.scala:48)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:64)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:266)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (bootstrapslider/compile:fullOptJS::webpack) java.lang.AssertionError: assertion failed: Webpack failed to create application bundle
```
So everything seems to be fine until this puzzling exception. In the scalajs-bundler directory/main, the jquery-stub.js file is properly copied. 

Any idea ?

**Comment by ramnivas** [comment]
I am facing what looks like the same issue. Everything is actually fine, if I (mentally) ignore the exception.

**Comment by cquiroz** [comment]
I'm being affected by this issue as I have other task that depend on `fullOptJS::webpack` and they fail even though `webpack` runs fine.

Looking at the code it seems that e.g. for a library it expects `webpack` to produce a file like `project-library.js` but that is not necessarily the case when using a custom webpack config. That triggers the assertions [here](https://github.com/scalacenter/scalajs-bundler/blob/master/sbt-scalajs-bundler/src/main/scala/scalajsbundler/Webpack.scala#L152) and [here](https://github.com/scalacenter/scalajs-bundler/blob/master/sbt-scalajs-bundler/src/main/scala/scalajsbundler/Webpack.scala#L192)

Can those assertions be simply removed?

**Comment by julienrf** [comment]
We should probably remove the line that throws that exception. I don’t even remember why it was introduced in the first place. Do you remember why it was useful, @easel?

**Comment by easel** [comment]
I think the assertion is there to ensure the rest of the pipeline continues successfully -- if we don't assert it's likely to blow up in hard-to-debug ways further down. It wouldn't be hard to read the output file out of the webpack.config.js, I'd probably do that prior to removing it entirely.

**Comment by hejfelix** [comment]
I'm having this problem in my build -- it basically means I can't rely on the exit code of SBT for the frontend build step. Is there a workaround?

**Comment by julienrf** [comment]
One currently applicable workaround would consist in manually creating a file there so that the assertion doesn’t fail…

A better solution has been discussed in #219, we need someone to take it over! Any volunteer?
