### ISSUE TITLE
Test execution fails with scalajs 0.6.22

### ISSUE THREAD

**Issue by Taig** [scalacenter/scalajs-bundler#208]
```
sbt:root>test
...
[info] Fast optimizing .../target/scala-2.12/scalajs-bundler/test/reactsjs-core-test-fastopt.js
[error] java.lang.NoSuchMethodError: org.scalajs.sbtplugin.FrameworkDetector.<init>(Lorg/scalajs/jsenv/JSEnv;Lorg/scalajs/core/tools/linker/backend/ModuleKind;Lscala/Option;)V
[error] 	at org.scalajs.sbtplugin.FrameworkDetectorWrapper.<init>(FrameworkDetectorWrapper.scala:8)
[error] 	at scalajsbundler.sbtplugin.ScalaJSBundlerPlugin$.$anonfun$testSettings$8(ScalaJSBundlerPlugin.scala:633)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:271)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] (core / Test / loadedTestFrameworks) java.lang.NoSuchMethodError: org.scalajs.sbtplugin.FrameworkDetector.<init>(Lorg/scalajs/jsenv/JSEnv;Lorg/scalajs/core/tools/linker/backend/ModuleKind;Lscala/Option;)V
[error] Total time: 11 s, completed Jan 25, 2018 9:39:42 PM
```

**Comment by sjrd** [comment]
@julienrf Ah ... that's what happens when [one hacks around package-private APIs](https://github.com/scalacenter/scalajs-bundler/blob/master/sbt-scalajs-bundler/src/main/scala/org/scalajs/sbtplugin/FrameworkDetectorWrapper.scala) 😅 

The good news is that in 0.6.22, a much better API has been made public right inside the test-adapter. So fixing this should be relatively easy and improve the codebase.

I suggest looking at the diff here for inspiration about what needs to change in scalajs-bundler: https://github.com/scala-js/scala-js/commit/22a8d7dc52669c537154f21519752a8b6680a174#diff-dd593403434ec9de3670cb5722f10171

**Comment by ngbinh** [comment]
this issue prevents us from upgrading to 0.6.22 :(

**Comment by cquiroz** [comment]
I'm seeing the same in all my projects. Can't upgrade to 0.6.22 due to this issue

**Comment by julienrf** [comment]
I guess this is going to block a few other people as well… Can someone try to solve it?

**Comment by julienrf** [comment]
I don’t know if this is going to work but if people are willing to pay to get it solved you can back this bounty: https://www.bountysource.com/issues/54238921-test-execution-fails-with-scalajs-0-6-22
Maybe that will encourage someone to contribute a fix!
