### ISSUE TITLE
additionalNpmConfig leads to mysterious `No webpack version defined` exception

### ISSUE THREAD

**Issue by pshirshov** [scalacenter/scalajs-bundler#275]
When you have `additionalNpmConfig in Compile` defined any `:webpack` invocation ends with.

```
[info] Writing scalajs.webpack.config.js
java.lang.RuntimeException: No webpack version defined
	at scala.sys.package$.error(package.scala:27)
	at scalajsbundler.Webpack$.writeConfigFile(Webpack.scala:153)
	at scalajsbundler.Webpack$.bundle(Webpack.scala:186)
	at scalajsbundler.sbtplugin.WebpackTasks$$anonfun$webpack$1$$anonfun$1.apply(WebpackTasks.scala:41)
	at scalajsbundler.sbtplugin.WebpackTasks$$anonfun$webpack$1$$anonfun$1.apply(WebpackTasks.scala:40)
	at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:253)
	at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:253)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:267)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:263)
	at sbt.Difference.apply(Tracked.scala:224)
	at sbt.Difference.apply(Tracked.scala:206)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:263)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:262)
	at sbt.Difference.apply(Tracked.scala:224)
	at sbt.Difference.apply(Tracked.scala:200)
	at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:262)
	at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:260)
	at scalajsbundler.sbtplugin.WebpackTasks$$anonfun$webpack$1.apply(WebpackTasks.scala:54)
	at scalajsbundler.sbtplugin.WebpackTasks$$anonfun$webpack$1.apply(WebpackTasks.scala:20)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[error] (compile:fastOptJS::webpack) No webpack version defined
```

I have modified scalajs tutorial to demonstrate the issue. The diff is trivial. Please find the demo here: https://github.com/pshirshov/scalajs-bundler-bug-webpack-version

Just run in the project root:

```
npm install jsdom
sbt clean fastOptJS:webpack
```

**Comment by julienrf** [comment]
Hey, the problem is that your `name` field is invalid. See the rules [here](https://docs.npmjs.com/files/package.json#name).

However, a bigger problem is that although `npm install` effectively *fails* when the name is invalid, it does not report an error but a warning (“npm WARN Invalid name: "Scala.js Tutorial"”) and exists with a successful status code… This means that I don’t see how we can detect that npm has failed.

**Comment by julienrf** [comment]
Besides that, the following changes will be required for your project: instead of using `jsDependencies` use `npmDependencies in Compile`, and instead of specifying the `jsEnv` to use, add the `requireJsDomEnv := true` setting.

**Comment by julienrf** [comment]
I would love to improve diagnostics, however in that specific case I’m not sure how we should proceed: npm only emits a warning (like a lot of other warnings that we can “safely” ignore) and returns a successful status code. There is nothing we can do other than parsing the text of each warning and checking whether it matches a given regexp or not, but I’d rather not hardcode such fragile logic in scalajs-bundler.

Hopefully, people searching for a similar error will eventually find this issue and this will “document” how to fix the problem.

**Comment by pshirshov** [comment]
I guess it's possible to use one of multiple validators available on npm.
Just install them before all the actions then run.

Or, at least, throw a more descriptive exception. Like "`devDependencies.webpack` is missing from package.json, most likely it means that your additionalNpmConfig contains invalid entries"
