### ISSUE TITLE
fastOptJS::webpack fails on Scala JS 0.6.14

### ISSUE THREAD

**Issue by shogowada** [scalacenter/scalajs-bundler#79]
I am using bundler 0.4.0.

I have upgraded my app's Scala JS to 0.6.14, and I started getting the following error on ```fastOptJS::webpack```.

```
[info] Fast optimizing /Users/shogowada/Projects/scalajs-reactjs/example/todo-app/target/scala-2.12/scalajs-bundler/main/scalajs-reactjs-example-todo-app-fastopt.js
[debug] Linker: Compute reachability: 102223 us
[debug] Linker: Assemble LinkedClasses: 55114 us
[debug] Basic Linking: 159919 us
[debug] Inc. optimizer: Batch mode: false
[debug] Inc. optimizer: Incremental part: 15126 us
[debug] Inc. optimizer: Optimizing 0 methods.
[debug] Inc. optimizer: Optimizer part: 165 us
[debug] Inc. optimizer: 26363 us
[debug] Refiner: Compute reachability: 160233 us
[debug] Refiner: Assemble LinkedClasses: 13323 us
[debug] Refiner: 173718 us
[debug] Emitter: Class tree cache stats: reused: 0 -- invalidated: 319
[debug] Emitter: Method tree cache stats: resued: 0 -- invalidated: 1489
[debug] Emitter (write output): 1095017 us
[debug] Global IR cache stats: reused: 117 -- invalidated: 88 -- trees read: 449
java.lang.NoSuchMethodError: org.scalajs.core.tools.javascript.Trees$VarDef.<init>(Lorg/scalajs/core/tools/javascript/Trees$Ident;Lorg/scalajs/core/tools/javascript/Trees$Tree;Lorg/scalajs/core/ir/Position;)V
        at scalajsbundler.util.JS$.let(JS.scala:73)
        at scalajsbundler.ReloadWorkflow$.writeFakeBundle(ReloadWorkflow.scala:53)
        at scalajsbundler.sbtplugin.ReloadWorkflowTasks$$anonfun$webpackTask$1.apply(ReloadWorkflowTasks.scala:22)
        at scalajsbundler.sbtplugin.ReloadWorkflowTasks$$anonfun$webpackTask$1.apply(ReloadWorkflowTasks.scala:18)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (exampleTodoApp/compile:fastOptJS::webpack) java.lang.NoSuchMethodError: org.scalajs.core.tools.javascript.Trees$VarDef.<init>(Lorg/scalajs/core/tools/javascript/Trees$Ident;Lorg/scalajs/core/tools/javascript/Trees$Tree;Lorg/scalajs/core/ir/Position;)V
```

I believe this is because Scala JS has changed the parameter type of ```VarDef``` class from

- ```(name: Ident, rhs: Tree)(implicit val pos: Position)``` to
- ```(name: Ident, rhs: Option[Tree])(implicit val pos: Position)```

starting from 0.6.14 (See https://github.com/scala-js/scala-js/commit/68634518a96bfdd98671f50f6c49910bfacbe30c#diff-4d512422fde665c4c5d713d24ddd3bffR63 for the diff).

This blocks dependent apps to upgrade to Scala JS 0.6.14.

**Comment by julienrf** [comment]
Indeed, you perfectly identified the issue. scalajs-bundler uses a part of the internal API of Scala.js, and this API changed between 0.6.13 and 0.6.14.

We should definitely publish a new version for Scala.js-0.6.14.

**Comment by Sebruck** [comment]
@julienrf I have a working version with scala.js 0.6.14 locally. @julienrf I'd like to file a PR, which branch can i use?

**Comment by julienrf** [comment]
Please use `master`
